# generator.py
"""Ollama-backed text generation for the RAG pipeline.

This module contains the concrete generator adapter responsible for sending
an already constructed RAG prompt to Ollama and returning generated text.

The actual HTTP behavior is intentionally not implemented during the skeleton
phase. Tests will define that behavior before production code is added.
"""

from __future__ import annotations

from typing import Final


# ============================================================
# Default configuration
# ============================================================

# Keep infrastructure defaults in one visible place so callers can override
# them without scattering Ollama-specific values throughout the application.
DEFAULT_OLLAMA_BASE_URL: Final[str] = "http://localhost:11434"
DEFAULT_OLLAMA_GENERATOR_MODEL: Final[str] = "llama3.2"
DEFAULT_REQUEST_TIMEOUT: Final[float] = 30.0


# ============================================================
# Generator implementation
# ============================================================

class OllamaGeneratorModel:
    """Generate grounded answers through Ollama's local HTTP API.

    This class is intended to satisfy the ``GeneratorModel`` protocol declared
    in ``integrator.py``. Explicit inheritance is unnecessary because Python
    protocols support structural typing: implementing ``generate`` with the
    expected signature is sufficient.

    Attributes are kept private because connection and model configuration are
    implementation details of this adapter, not part of the generator contract.
    """

    def __init__(
        self,
        ollama_base_url: str = DEFAULT_OLLAMA_BASE_URL,
        model: str = DEFAULT_OLLAMA_GENERATOR_MODEL,
        timeout: float = DEFAULT_REQUEST_TIMEOUT,
    ) -> None:
        """Store the configuration required for future Ollama requests.

        Args:
            ollama_base_url:
                Base URL of the Ollama server.
            model:
                Name of the Ollama text-generation model.
            timeout:
                Maximum duration, in seconds, of a generation request.

        Validation and HTTP-client setup will be introduced only after tests
        specify their expected behavior.
        """
        self._ollama_base_url = ollama_base_url
        self._model = model
        self._timeout = timeout

    def generate(self, prompt: str) -> str:
        """Generate an answer for a fully constructed RAG prompt.

        Args:
            prompt:
                The grounded prompt prepared by ``RAGIntegrator``, containing
                both the user's question and retrieved context.

        Returns:
            The text generated by Ollama.

        Raises:
            NotImplementedError:
                Always during the skeleton phase.
        """
        # RED/GREEN boundary:
        # A later failing test will specify request validation, the Ollama API
        # payload, response parsing, and error translation before we implement
        # any of those behaviors.
        raise NotImplementedError(
            "OllamaGeneratorModel.generate() is not implemented yet."
        )